steps:
  # 1. Build the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push the Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

  # 3. Update the MIGRATION Job with the new Image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy migrate-job \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA \
          --region $_REGION

  # 4. Update the COLLECTSTATIC Job with the new Image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs deploy collectstatic-job \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA \
          --region $_REGION

  # 5. Execute the Migration Job (Wait for success)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'jobs', 'execute', 'migrate-job', '--region', '$_REGION', '--wait']

  # 6. Execute the Collectstatic Job (Wait for success)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'jobs', 'execute', 'collectstatic-job', '--region', '$_REGION', '--wait']

  # 7. Deploy the Web Service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'  # REPLACE with your actual Service Name
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'

substitutions:
  _SERVICE_NAME: 'portfolio'
  _REGION: 'us-central1'
  _MEMORY: '512Mi'
  _CPU: '1'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

timeout: '1200s'
